version: '3'
services:
    apache:
        build: .docker/apache
        container_name: lpa_sf6_apache
        ports:
          - "8081:80"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www/lpa_sf6
          - .docker/data/apache:/var/log/apache2
        environment:
          PHP_IDE_CONFIG: serverName=lpa_sf6.docker
        depends_on:
          - php

    php:
        build: .docker/php
        container_name: lpa_sf6_php
        volumes:
          - .:/var/www/lpa_sf6
        environment:
          - mailcatcher_host=lpa_sf6_mailcatcher
        depends_on:
          - mailcatcher

    mailcatcher:
        container_name: lpa_sf6_mailcatcher
        restart: on-failure:10
        image: dockage/mailcatcher:0.8.2
        ports:
            - "1081:1080"
            - "1026:1025"

    mysql:
        image: mysql:8.0.31
        command: ['--default-authentication-plugin=mysql_native_password']
        container_name: lpa_sf6_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lpa_sf6
            MYSQL_USER: lpa_sf6
            MYSQL_PASSWORD: lpa_sf6

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lpa_sf6_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - "8090:80"
        links:
            - mysql