vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/deals
            upload_destination: '%kernel.project_dir%/public/images/deals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
